# Generated by Django 6.0.2 on 2026-03-12 11:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAIProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project_number', models.CharField(max_length=100, unique=True, verbose_name='项目编号')),
                ('project_name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('IN_PROGRESS', '进行中'), ('PENDING_REVIEW', '待审核'), ('COMPLETED', '已完成'), ('ARCHIVED', '已归档')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='完成进度')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='目标日期')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': 'FAI项目',
                'verbose_name_plural': 'FAI项目',
                'db_table': 'fai_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_code', models.CharField(choices=[('PRODUCT_INFO', '产品信息'), ('DRAWING_IMPORT', '图纸导入'), ('OCR_RECOGNITION', 'OCR识别'), ('DIMENSION_TABLE', '尺寸公差表'), ('MEASUREMENT', '测量数据'), ('ANALYSIS', '统计分析'), ('REPORT', '报告生成'), ('APPROVAL', '审批流程')], max_length=30, verbose_name='步骤代码')),
                ('step_name', models.CharField(max_length=100, verbose_name='步骤名称')),
                ('step_order', models.PositiveIntegerField(default=1, verbose_name='步骤顺序')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('IN_PROGRESS', '进行中'), ('COMPLETED', '已完成'), ('SKIPPED', '已跳过')], default='PENDING', max_length=20, verbose_name='状态')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='完成人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.faiproject', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目步骤',
                'verbose_name_plural': '项目步骤',
                'db_table': 'project_steps',
                'ordering': ['step_order'],
                'unique_together': {('project', 'step_code')},
            },
        ),
    ]
