# Generated by Django 5.2 on 2026-04-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_faiproject_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(blank=True, verbose_name='配置值')),
                ('category', models.CharField(choices=[('ocr', 'OCR配置'), ('api', 'API配置'), ('storage', '存储配置'), ('email', '邮件配置'), ('system', '系统配置')], default='system', max_length=20, verbose_name='分类')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='描述')),
                ('is_secret', models.BooleanField(default=False, verbose_name='是否敏感')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'system_configs',
                'ordering': ['category', 'key'],
            },
        ),
    ]
