# Generated by Django 5.1.4 on 2026-02-14 03:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_id', models.CharField(max_length=100, unique=True, verbose_name='设备编号')),
                ('equipment_name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('equipment_type', models.CharField(choices=[('CMM', '三坐标测量机'), ('OPTICAL', '光学测量仪'), ('LASER', '激光扫描仪'), ('VISION', '影像测量仪'), ('MECHANICAL', '机械测量设备'), ('OTHER', '其他')], max_length=20, verbose_name='设备类型')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='制造商')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='序列号')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('port', models.PositiveIntegerField(blank=True, null=True, verbose_name='端口')),
                ('connection_string', models.CharField(blank=True, max_length=500, verbose_name='连接字符串')),
                ('status', models.CharField(choices=[('ACTIVE', '正常'), ('MAINTENANCE', '维护中'), ('CALIBRATION', '校准中'), ('INACTIVE', '停用')], default='ACTIVE', max_length=20, verbose_name='状态')),
                ('last_calibration_date', models.DateField(blank=True, null=True, verbose_name='上次校准日期')),
                ('next_calibration_date', models.DateField(blank=True, null=True, verbose_name='下次校准日期')),
                ('calibration_certificate', models.CharField(blank=True, max_length=100, verbose_name='校准证书')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='存放位置')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '测量设备',
                'verbose_name_plural': '测量设备',
                'db_table': 'equipment',
                'ordering': ['equipment_id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CONNECTED', '已连接'), ('DISCONNECTED', '已断开'), ('ERROR', '错误')], max_length=20, verbose_name='状态')),
                ('connected_at', models.DateTimeField(auto_now_add=True, verbose_name='连接时间')),
                ('disconnected_at', models.DateTimeField(blank=True, null=True, verbose_name='断开时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='equipment.equipment', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备连接',
                'verbose_name_plural': '设备连接',
                'db_table': 'equipment_connections',
                'ordering': ['-connected_at'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementDataImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_data', models.BinaryField(blank=True, null=True, verbose_name='文件数据')),
                ('parsed_data', models.JSONField(blank=True, default=dict, verbose_name='解析数据')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('PROCESSING', '处理中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='PENDING', max_length=20, verbose_name='状态')),
                ('total_records', models.PositiveIntegerField(default=0, verbose_name='总记录数')),
                ('imported_records', models.PositiveIntegerField(default=0, verbose_name='已导入记录数')),
                ('error_records', models.PositiveIntegerField(default=0, verbose_name='错误记录数')),
                ('error_log', models.TextField(blank=True, verbose_name='错误日志')),
                ('imported_at', models.DateTimeField(blank=True, null=True, verbose_name='导入时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='equipment.equipment', verbose_name='设备')),
            ],
            options={
                'verbose_name': '测量数据导入',
                'verbose_name_plural': '测量数据导入',
                'db_table': 'measurement_imports',
                'ordering': ['-created_at'],
            },
        ),
    ]
