# Generated by Django 5.1.4 on 2026-02-14 03:38

import django.db.models.deletion
import parts.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CADExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_data', models.JSONField(blank=True, default=dict, verbose_name='提取数据')),
                ('status', models.CharField(choices=[('PENDING', '待解析'), ('PROCESSING', '解析中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='PENDING', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('extracted_at', models.DateTimeField(blank=True, null=True, verbose_name='提取时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'CAD解析记录',
                'verbose_name_plural': 'CAD解析记录',
                'db_table': 'cad_extractions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim_id', models.CharField(max_length=50, verbose_name='尺寸ID')),
                ('dim_type', models.CharField(choices=[('LINEAR', '线性尺寸'), ('ANGULAR', '角度尺寸'), ('DIAMETER', '直径'), ('RADIUS', '半径'), ('GD_T', '形位公差'), ('SURFACE', '表面粗糙度')], max_length=20, verbose_name='尺寸类型')),
                ('name', models.CharField(max_length=200, verbose_name='尺寸名称')),
                ('nominal_value', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='理论值')),
                ('upper_tolerance', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='上公差')),
                ('lower_tolerance', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='下公差')),
                ('unit', models.CharField(default='mm', max_length=10, verbose_name='单位')),
                ('is_critical', models.BooleanField(default=False, verbose_name='是否关键特性')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='parts.cadextraction', verbose_name='解析记录')),
            ],
            options={
                'verbose_name': '尺寸',
                'verbose_name_plural': '尺寸',
                'db_table': 'dimensions',
                'ordering': ['dim_id'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('part_number', models.CharField(max_length=100, unique=True, verbose_name='零件编号')),
                ('part_name', models.CharField(max_length=200, verbose_name='零件名称')),
                ('revision', models.CharField(default='A', max_length=20, verbose_name='版本号')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('cad_file', models.FileField(blank=True, null=True, upload_to=parts.models.cad_file_upload_path, verbose_name='CAD文件')),
                ('cad_file_type', models.CharField(blank=True, max_length=20, verbose_name='CAD文件类型')),
                ('drawing_file', models.FileField(blank=True, null=True, upload_to=parts.models.drawing_upload_path, verbose_name='图纸文件')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='材料')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='重量(kg)')),
                ('surface_treatment', models.CharField(blank=True, max_length=200, verbose_name='表面处理')),
                ('customer', models.CharField(blank=True, max_length=200, verbose_name='客户')),
                ('customer_part_number', models.CharField(blank=True, max_length=100, verbose_name='客户零件编号')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('ACTIVE', '激活'), ('OBSOLETE', '作废'), ('PENDING', '待审核')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '零件',
                'verbose_name_plural': '零件',
                'db_table': 'parts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cadextraction',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='parts.part', verbose_name='零件'),
        ),
    ]
