# Generated by Django 6.0.2 on 2026-03-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='batch_serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='批次/序列号'),
        ),
        migrations.AddField(
            model_name='part',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='单位/部门'),
        ),
        migrations.AddField(
            model_name='part',
            name='operator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='操作者'),
        ),
        migrations.AddField(
            model_name='part',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='订单号'),
        ),
        # 整数字段允许为空，避免已有数据问题
        migrations.AddField(
            model_name='part',
            name='fai_quantity',
            field=models.PositiveIntegerField(null=True, blank=True, verbose_name='首件数量'),
        ),
        migrations.AddField(
            model_name='part',
            name='production_quantity',
            field=models.PositiveIntegerField(null=True, blank=True, verbose_name='生产数量'),
        ),
    ]
