# Generated by Django 6.0.2 on 2026-03-26 10:07

import parts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_fix_fai_quantity_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='支持格式: PDF', null=True, upload_to=parts.models.document_upload_path, verbose_name='PDF文档'),
        ),
        migrations.AlterField(
            model_name='part',
            name='cad_file',
            field=models.FileField(blank=True, help_text='支持格式: DWG, DXF, SLDPRT, CATPART, PRT, STEP, STP', null=True, upload_to=parts.models.cad_file_upload_path, verbose_name='CAD文件'),
        ),
        migrations.AlterField(
            model_name='part',
            name='drawing_file',
            field=models.FileField(blank=True, help_text='支持格式: PDF, PNG, JPG, DWG, DXF', null=True, upload_to=parts.models.drawing_upload_path, verbose_name='图纸文件'),
        ),
        migrations.AlterField(
            model_name='part',
            name='fai_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='首件数量'),
        ),
        migrations.AlterField(
            model_name='part',
            name='production_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='生产数量'),
        ),
    ]
