# Generated by Django 6.0.2 on 2026-03-28 05:30

import django.db.models.deletion
import parts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_add_pdf_file_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='cad_file',
            field=models.FileField(blank=True, help_text='仅存储，不支持解析。格式: DWG, DXF, SLDPRT, CATPART, PRT, STEP', null=True, upload_to=parts.models.cad_file_upload_path, verbose_name='CAD文件'),
        ),
        migrations.AlterField(
            model_name='part',
            name='drawing_file',
            field=models.FileField(blank=True, help_text='支持OCR识别。格式: PNG, JPG, BMP, GIF', null=True, upload_to=parts.models.drawing_upload_path, verbose_name='图片文件'),
        ),
        migrations.AlterField(
            model_name='part',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='支持OCR识别。格式: PDF', null=True, upload_to=parts.models.document_upload_path, verbose_name='PDF文档'),
        ),
        migrations.CreateModel(
            name='DimensionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('template_type', models.CharField(choices=[('SHAFT', '轴类零件'), ('PLATE', '板类零件'), ('HOUSING', '壳体零件'), ('CUSTOM', '自定义')], default='CUSTOM', max_length=20, verbose_name='模板类型')),
                ('dimensions_data', models.JSONField(default=list, verbose_name='尺寸数据')),
                ('is_public', models.BooleanField(default=True, verbose_name='公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '尺寸模板',
                'verbose_name_plural': '尺寸模板',
                'db_table': 'dimension_templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
