# Generated by Django 5.2 on 2026-04-01
# 添加 PartAttachment 模型（注：model_3d_file_type 已在 0006 中添加）

import django.db.models.deletion
import parts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_add_drawing_review_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 注意：model_3d_file_type 已在 0006 迁移中添加，这里不再重复添加
        
        # 修改 model_3d_file 字段（如果需要）
        migrations.AlterField(
            model_name='part',
            name='model_3d_file',
            field=models.FileField(blank=True, help_text='支持解析。格式: STEP(.stp/.step), IGES(.igs/.iges), STL, OBJ, PLY', null=True, upload_to=parts.models.model_3d_upload_path, verbose_name='3D模型文件'),
        ),
        # 创建 PartAttachment 模型
        migrations.CreateModel(
            name='PartAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='part_attachments/%Y%m/%d/', verbose_name='附件文件')),
                ('file_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_type', models.CharField(choices=[('PDF', 'PDF文档'), ('IMAGE', '图片文件'), ('CAD', 'CAD文件'), ('MODEL_3D', '3D模型'), ('OTHER', '其他')], max_length=20, verbose_name='文件类型')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('ocr_status', models.CharField(choices=[('PENDING', '待识别'), ('PROCESSING', '识别中'), ('COMPLETED', '识别完成'), ('FAILED', '识别失败')], default='PENDING', max_length=20, verbose_name='OCR状态')),
                ('ocr_data', models.JSONField(blank=True, default=dict, verbose_name='OCR识别数据')),
                ('ocr_error', models.TextField(blank=True, verbose_name='OCR错误信息')),
                ('extracted_features', models.JSONField(blank=True, default=dict, verbose_name='提取的特征')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='描述')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='parts.part', verbose_name='零件')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '零件附件',
                'verbose_name_plural': '零件附件',
                'db_table': 'part_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
