# Generated by Django 5.2 on 2026-04-01
# 添加 file_metadata 字段存储原始文件名等信息

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_part_model_3d_file_type_alter_part_model_3d_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='file_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='文件元信息'),
        ),
    ]
