# Generated by Django 5.2 on 2026-04-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_part_file_metadata'),
    ]

    operations = [
        # 修复 model_3d_file_type 字段，添加 null=True
        migrations.AlterField(
            model_name='part',
            name='model_3d_file_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='3D文件类型'),
        ),
        # 修复 cad_file_type 字段，添加 null=True（防止类似问题）
        migrations.AlterField(
            model_name='part',
            name='cad_file_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CAD文件类型'),
        ),
    ]
