# Generated by Django 5.2 on 2026-04-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_fix_model_3d_file_type_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='cad_file_type',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='CAD文件类型'),
        ),
        migrations.AlterField(
            model_name='part',
            name='model_3d_file_type',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='3D文件类型'),
        ),
    ]
