# Generated by Django 5.2 on 2026-06-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0011_alter_part_cad_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='tolerance_verified',
            field=models.BooleanField(default=False, help_text='AI/OCR识别结果默认未核实，需人工确认或修正后才能生成正式检验特性', verbose_name='公差已人工核实'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='lower_tolerance',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='为空表示未识别到明确标注或为单侧公差，需人工核实', max_digits=10, null=True, verbose_name='下公差'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='upper_tolerance',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='为空表示未识别到明确标注或为单侧公差，需人工核实', max_digits=10, null=True, verbose_name='上公差'),
        ),
    ]
