# Generated by Django 5.2 on 2026-06-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0012_dimension_tolerance_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='position',
            field=models.JSONField(blank=True, help_text='格式{"x": 0-100, "y": 0-100}，表示该尺寸标注在图纸图片中的百分比坐标，用于气泡图定位；为空表示识别引擎未返回位置信息', null=True, verbose_name='图纸标注位置'),
        ),
    ]
