# Generated by Django 5.2 on 2026-06-20 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0013_dimension_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cadextraction',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='已人工复核'),
        ),
        migrations.AddField(
            model_name='cadextraction',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='复核时间'),
        ),
        migrations.AddField(
            model_name='cadextraction',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_extractions', to=settings.AUTH_USER_MODEL, verbose_name='复核人'),
        ),
    ]
