# Generated by Django 5.1.4 on 2026-02-14 03:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_type', models.CharField(choices=[('PLAN_APPROVAL', '检验计划审批'), ('REPORT_APPROVAL', '检验报告审批')], max_length=50, verbose_name='工作流类型')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('IN_PROGRESS', '进行中'), ('COMPLETED', '已完成'), ('REJECTED', '已拒绝'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='状态')),
                ('current_step', models.PositiveIntegerField(default=1, verbose_name='当前步骤')),
                ('initiated_at', models.DateTimeField(auto_now_add=True, verbose_name='发起时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_workflows', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='inspections.inspectionplan', verbose_name='检验计划')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='reports.inspectionreport', verbose_name='检验报告')),
            ],
            options={
                'verbose_name': '审批工作流',
                'verbose_name_plural': '审批工作流',
                'db_table': 'approval_workflows',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField(verbose_name='步骤序号')),
                ('step_name', models.CharField(choices=[('SUBMIT', '提交'), ('REVIEW', '审核'), ('APPROVE', '批准')], max_length=50, verbose_name='步骤名称')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('APPROVED', '已通过'), ('REJECTED', '已拒绝'), ('SKIPPED', '已跳过')], default='PENDING', max_length=20, verbose_name='状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('comments', models.TextField(blank=True, verbose_name='审批意见')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.approvalworkflow', verbose_name='工作流')),
            ],
            options={
                'verbose_name': '审批步骤',
                'verbose_name_plural': '审批步骤',
                'db_table': 'approval_steps',
                'ordering': ['step_number'],
                'unique_together': {('workflow', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='ElectronicSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='签名图片')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='签名时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='用户代理')),
                ('digital_hash', models.CharField(blank=True, max_length=128, verbose_name='数字哈希')),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='workflows.approvalstep', verbose_name='审批步骤')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='签名用户')),
            ],
            options={
                'verbose_name': '电子签名',
                'verbose_name_plural': '电子签名',
                'db_table': 'electronic_signatures',
            },
        ),
    ]
