# Generated by Django 6.0.2 on 2026-03-12 11:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonConformanceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ncr_number', models.CharField(max_length=50, unique=True, verbose_name='NCR编号')),
                ('product_name', models.CharField(max_length=200, verbose_name='品名')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='规格')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='批次号')),
                ('department_code', models.CharField(blank=True, max_length=50, verbose_name='科号')),
                ('problem_type', models.CharField(choices=[('DIMENSION', '尺寸超差'), ('APPEARANCE', '外观缺陷'), ('MATERIAL', '材料问题'), ('PROCESS', '工艺问题'), ('ASSEMBLY', '装配问题'), ('OTHER', '其他')], max_length=20, verbose_name='问题类型')),
                ('problem_description', models.TextField(verbose_name='问题描述')),
                ('defect_phenomenon', models.CharField(blank=True, max_length=500, verbose_name='不良现象')),
                ('supply_method', models.CharField(choices=[('INTERNAL', '内部加工'), ('EXTERNAL', '外协加工'), ('PURCHASED', '外购件')], default='INTERNAL', max_length=20, verbose_name='供应方式')),
                ('supplier_name', models.CharField(blank=True, max_length=200, verbose_name='供方名称')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='交货日期')),
                ('status', models.CharField(choices=[('OPEN', '待处理'), ('IN_PROGRESS', '处理中'), ('PENDING_REVIEW', '待审核'), ('CLOSED', '已关闭'), ('CANCELLED', '已取消')], default='OPEN', max_length=20, verbose_name='状态')),
                ('inspected_at', models.DateTimeField(blank=True, null=True, verbose_name='检验时间')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='ncr_attachments/', verbose_name='附件')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_ncrs', to=settings.AUTH_USER_MODEL, verbose_name='检验人')),
                ('measurement_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_conformances', to='measurements.measurementrecord', verbose_name='测量记录')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_ncrs', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '不合格品报告',
                'verbose_name_plural': '不合格品报告',
                'db_table': 'non_conformance_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NonConformanceAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('REWORK', '返工'), ('REPAIR', '返修'), ('SCRAP', '报废'), ('CONCESSION', '让步接收'), ('RETURN', '退货'), ('REVIEW', '评审')], max_length=20, verbose_name='处理方式')),
                ('action_description', models.TextField(verbose_name='处理措施描述')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('status', models.CharField(choices=[('PENDING', '待执行'), ('IN_PROGRESS', '执行中'), ('COMPLETED', '已完成'), ('VERIFIED', '已验证')], default='PENDING', max_length=20, verbose_name='状态')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('completion_notes', models.TextField(blank=True, verbose_name='完成备注')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='验证时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_actions', to=settings.AUTH_USER_MODEL, verbose_name='验证人')),
                ('ncr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflows.nonconformancereport', verbose_name='不合格品报告')),
            ],
            options={
                'verbose_name': '不合格品处理措施',
                'verbose_name_plural': '不合格品处理措施',
                'db_table': 'non_conformance_actions',
                'ordering': ['created_at'],
            },
        ),
    ]
