# Generated by Django 5.1.4 on 2026-02-14 03:38

import django.db.models.deletion
import reports.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        ('measurements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('standard', models.CharField(choices=[('AS9102', 'AS9102航空航天'), ('PPAP', 'PPAP生产件批准'), ('FAI', '首件检验'), ('CUSTOM', '自定义')], max_length=20, verbose_name='标准类型')),
                ('template_file', models.FileField(blank=True, null=True, upload_to='templates/', verbose_name='模板文件')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '报告模板',
                'verbose_name_plural': '报告模板',
                'db_table': 'report_templates',
            },
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_number', models.CharField(max_length=100, unique=True, verbose_name='报告编号')),
                ('title', models.CharField(max_length=200, verbose_name='报告标题')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('GENERATING', '生成中'), ('COMPLETED', '已完成'), ('PUBLISHED', '已发布'), ('ARCHIVED', '已归档')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=reports.models.report_upload_path, verbose_name='PDF文件')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='生成时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('summary', models.TextField(blank=True, verbose_name='报告总结')),
                ('conclusion', models.CharField(blank=True, max_length=20, verbose_name='结论')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='measurements.measurementbatch', verbose_name='测量批次')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='生成人')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='inspections.inspectionplan', verbose_name='检验计划')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_reports', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reporttemplate', verbose_name='报告模板')),
            ],
            options={
                'verbose_name': '检验报告',
                'verbose_name_plural': '检验报告',
                'db_table': 'inspection_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
