# Generated by Django 5.2 on 2026-06-20 08:20

import django.db.models.deletion
import reports.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalTestRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=200, verbose_name='测试项目')),
                ('spec_reference', models.CharField(blank=True, max_length=200, verbose_name='依据规范/图纸要求')),
                ('result_summary', models.TextField(blank=True, verbose_name='测试结果摘要')),
                ('compliant', models.BooleanField(default=True, verbose_name='符合要求')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=reports.models.form2_attachment_upload_path, verbose_name='测试报告附件')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functional_tests', to='reports.inspectionreport', verbose_name='检验报告')),
            ],
            options={
                'verbose_name': 'Form2-功能测试记录',
                'verbose_name_plural': 'Form2-功能测试记录',
                'db_table': 'functional_test_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_spec', models.CharField(max_length=200, verbose_name='材料规范/牌号')),
                ('cert_number', models.CharField(blank=True, max_length=100, verbose_name='证书编号')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='供应商')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='批次/炉批号')),
                ('compliant', models.BooleanField(default=True, verbose_name='符合要求')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=reports.models.form2_attachment_upload_path, verbose_name='证书附件')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_certifications', to='reports.inspectionreport', verbose_name='检验报告')),
            ],
            options={
                'verbose_name': 'Form2-原材料证书',
                'verbose_name_plural': 'Form2-原材料证书',
                'db_table': 'material_certifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialProcessRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process_type', models.CharField(choices=[('HEAT_TREATMENT', '热处理'), ('NDT', '无损检测'), ('PLATING', '电镀'), ('WELDING', '焊接'), ('COATING', '涂层/喷涂'), ('PAINTING', '涂装'), ('OTHER', '其他')], max_length=20, verbose_name='工艺类型')),
                ('spec_number', models.CharField(blank=True, max_length=100, verbose_name='执行规范编号')),
                ('processor', models.CharField(blank=True, max_length=200, verbose_name='工艺供方/承做单位')),
                ('cert_number', models.CharField(blank=True, max_length=100, verbose_name='合格证编号')),
                ('compliant', models.BooleanField(default=True, verbose_name='符合要求')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=reports.models.form2_attachment_upload_path, verbose_name='合格证附件')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_processes', to='reports.inspectionreport', verbose_name='检验报告')),
            ],
            options={
                'verbose_name': 'Form2-特殊工艺记录',
                'verbose_name_plural': 'Form2-特殊工艺记录',
                'db_table': 'special_process_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
