# Generated by Django 5.1.4 on 2026-02-14 03:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100, unique=True, verbose_name='批次号')),
                ('sample_size', models.PositiveIntegerField(default=1, verbose_name='样本数量')),
                ('equipment_type', models.CharField(max_length=50, verbose_name='设备类型')),
                ('equipment_id', models.CharField(max_length=100, verbose_name='设备编号')),
                ('equipment_name', models.CharField(blank=True, max_length=200, verbose_name='设备名称')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='温度(℃)')),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='湿度(%)')),
                ('status', models.CharField(choices=[('IN_PROGRESS', '测量中'), ('COMPLETED', '已完成'), ('REVIEWED', '已审核'), ('APPROVED', '已批准')], default='IN_PROGRESS', max_length=20, verbose_name='状态')),
                ('measured_at', models.DateTimeField(verbose_name='测量时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('measured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='测量人员')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inspections.inspectionplan', verbose_name='检验计划')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_batches', to=settings.AUTH_USER_MODEL, verbose_name='审核人员')),
            ],
            options={
                'verbose_name': '测量批次',
                'verbose_name_plural': '测量批次',
                'db_table': 'measurement_batches',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_number', models.PositiveIntegerField(default=1, verbose_name='样本序号')),
                ('measured_value', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='实测值')),
                ('deviation', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='偏差')),
                ('status', models.CharField(choices=[('PASS', '通过'), ('FAIL', '失败'), ('PENDING', '待定')], max_length=20, verbose_name='状态')),
                ('measured_at', models.DateTimeField(auto_now_add=True, verbose_name='测量时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='measurements.measurementbatch', verbose_name='测量批次')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='inspections.inspectioncharacteristic', verbose_name='检验特性')),
            ],
            options={
                'verbose_name': '测量记录',
                'verbose_name_plural': '测量记录',
                'db_table': 'measurement_records',
                'ordering': ['characteristic__sequence', 'sample_number'],
                'unique_together': {('batch', 'characteristic', 'sample_number')},
            },
        ),
        migrations.CreateModel(
            name='StatisticalAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_count', models.PositiveIntegerField(verbose_name='样本数')),
                ('mean', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='平均值')),
                ('std_dev', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='标准差')),
                ('min_value', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='最小值')),
                ('max_value', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='最大值')),
                ('range_value', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='极差')),
                ('cp', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cp')),
                ('cpk', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Cpk')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='计算时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='measurements.measurementbatch', verbose_name='测量批次')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='inspections.inspectioncharacteristic', verbose_name='检验特性')),
            ],
            options={
                'verbose_name': '统计分析',
                'verbose_name_plural': '统计分析',
                'db_table': 'statistical_analyses',
                'unique_together': {('characteristic', 'batch')},
            },
        ),
    ]
