# Generated by Django 6.0.2 on 2026-03-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_fix_batch_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementbatch',
            options={'ordering': ['-created_at'], 'verbose_name': '测量批次', 'verbose_name_plural': '测量批次'},
        ),
        migrations.AlterField(
            model_name='measurementbatch',
            name='equipment_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='设备名称'),
        ),
    ]
