# Generated by Django 5.1.4 on 2026-02-14 03:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('code', models.CharField(choices=[('DIMENSION', '尺寸特性'), ('PROCESS', '工艺特性'), ('MATERIAL', '材料特性'), ('ASSEMBLY', '装配特性'), ('APPEARANCE', '外观特性')], max_length=20, unique=True, verbose_name='分类代码')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '特性分类',
                'verbose_name_plural': '特性分类',
                'db_table': 'characteristic_categories',
            },
        ),
        migrations.CreateModel(
            name='InspectionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('plan_number', models.CharField(max_length=100, unique=True, verbose_name='计划编号')),
                ('plan_name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('standard', models.CharField(choices=[('AS9102', 'AS9102航空航天'), ('PPAP', 'PPAP生产件批准'), ('FAI', '首件检验'), ('CUSTOM', '自定义')], default='AS9102', max_length=20, verbose_name='标准类型')),
                ('sample_size', models.PositiveIntegerField(default=1, verbose_name='样本数量')),
                ('description', models.TextField(blank=True, verbose_name='计划描述')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING_REVIEW', '待审核'), ('ACTIVE', '激活'), ('IN_PROGRESS', '执行中'), ('COMPLETED', '已完成'), ('ARCHIVED', '已归档')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='批准时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_plans', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_plans', to='parts.part', verbose_name='零件')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '检验计划',
                'verbose_name_plural': '检验计划',
                'db_table': 'inspection_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionCharacteristic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('char_number', models.CharField(max_length=50, verbose_name='特性编号')),
                ('char_name', models.CharField(max_length=200, verbose_name='特性名称')),
                ('char_type', models.CharField(choices=[('DIMENSION', '尺寸'), ('ANGULAR', '角度'), ('GD_T', '形位公差'), ('SURFACE', '表面粗糙度'), ('HARDNESS', '硬度'), ('OTHER', '其他')], max_length=20, verbose_name='特性类型')),
                ('nominal_value', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='理论值')),
                ('upper_tolerance', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='上公差')),
                ('lower_tolerance', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='下公差')),
                ('unit', models.CharField(default='mm', max_length=10, verbose_name='单位')),
                ('measurement_method', models.CharField(choices=[('CMM', '三坐标测量'), ('OPTICAL', '光学测量'), ('MECHANICAL', '机械测量'), ('VISUAL', '目视检查'), ('LASER', '激光扫描'), ('OTHER', '其他')], default='CMM', max_length=20, verbose_name='测量方法')),
                ('gage_id', models.CharField(blank=True, max_length=50, verbose_name='量具编号')),
                ('gage_name', models.CharField(blank=True, max_length=100, verbose_name='量具名称')),
                ('is_critical', models.BooleanField(default=False, verbose_name='关键特性')),
                ('is_key_characteristic', models.BooleanField(default=False, verbose_name='关键特性(KC)')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='序号')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('drawing_reference', models.CharField(blank=True, max_length=100, verbose_name='图纸参考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.characteristiccategory', verbose_name='特性分类')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='inspections.inspectionplan', verbose_name='检验计划')),
            ],
            options={
                'verbose_name': '检验特性',
                'verbose_name_plural': '检验特性',
                'db_table': 'inspection_characteristics',
                'ordering': ['sequence', 'char_number'],
                'unique_together': {('plan', 'char_number')},
            },
        ),
    ]
