# Generated by Django 5.2 on 2026-06-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectioncharacteristic',
            name='lower_tolerance',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, help_text='留空表示无下限', max_digits=10, null=True, verbose_name='下公差'),
        ),
        migrations.AlterField(
            model_name='inspectioncharacteristic',
            name='upper_tolerance',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, help_text='留空表示无上限（如平面度、位置度等单侧形位公差）', max_digits=10, null=True, verbose_name='上公差'),
        ),
    ]
